language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t wschcom/docker-react -f Dockerfile.dev .

script:
  - docker run wschcom/docker-react npm run test -- --coverage