os: linux
dist: xenial
language: generic 
services:
  - docker

before_install:
  - docker build -t wschcom/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wschcom/docker-react npm run test