FROM node:16-alpine

USER node

WORKDIR '/app'

COPY --chown=node:node package.json .

RUN npm install

RUN mkdir -p /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache

#RUN chown -R node:node node_modules

COPY --chown=node:node . .

CMD ["npm", "run", "start"]