FROM node:16-alpine

USER node

WORKDIR '/app'

COPY --chown=node:node package.json .

RUN npm install

RUN sudo chown -R node:node /app/node_modules/

COPY --chown=node:node  . .

CMD ["npm", "run", "start"]