FROM node:16-alpine

USER node

WORKDIR '/app'

COPY --chown=$(whoami):$(whoami) package.json .

RUN npm install

RUN sudo chown -R $(whoami):$(whoami) /app/node_modules/

COPY --chown=$(whoami):$(whoami)  . .

CMD ["npm", "run", "start"]